apiVersion: v1
kind: Service
metadata:
  name: node-app-service
spec:
  selector:
    app: train-schedule
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 8081
    nodePort: 31110